spring:
  security:
    user:
      name: ${SECURITY-USER-NAME:user}
      password: ${SECURITY-USER-PASSWORD:password}
  datasource:
    url: ${DATABASE-URL:jdbc:postgresql://localhost:5432/friends_book}
    username: ${DATABASE-USERNAME:postgres}
    password: ${DATABASE-USER-PASSWORD:password}
    driver-class-name: ${DRIVER-CLASS-NAME:org.postgresql.Driver}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}