spring:
  security:
    user:
      name: ${SECURITY-USER-NAME}
      password: ${SECURITY-USER-PASSWORD}
  datasource:    url: ${DATABASE-URL}
    username: ${DATABASE-USERNAME}
    password: ${DATABASE-USER-PASSWORD}
    driver-class-name: ${DRIVER-CLASS-NAME}
eureka:
  instance:
    non-secure-port: 80
    hostname: <appname>.herokuapp.com